### ISSUE TITLE
Add Slack notifications for workflows

### ISSUE THREAD

**Issue by jwulf** [camunda/camunda-8-js-sdk#123]
Workflow fragment: 

```yaml
  Post-Failure:
    needs: Build_nightly
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      uses: slackapi/slack-github-action@v1.15.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-message: "Nightly build failed. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to the build.>"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```
